/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java_linkedlist;

import java_linkedlist.LinkedList.List;

public class App {

    public static void main(String[] args) {
        List<Integer> list = new List<>();

        list.add(2);
        list.add(3);
        list.add(0);
        list.add(1);
        list.add(4);
        list.add(5);

        System.out.println(list);
    }
}
